server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehicles
          uri: lb://vehicles
          predicates:
            - Path=/api/vehicles/**
        - id: repairs
          uri: lb://repairs
          predicates:
            - Path=/api/repairs/**
        - id: repairs-list
          uri: lb://repairs-list
          predicates:
            - Path=/api/repair-list/**
        - id: reports
          uri: lb://reports
          predicates:
            - Path=/api/reports/**
        - id: bonuses
          uri: lb://bonuses
          predicates:
            - Path=/api/bonuses/**