server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehicles
          uri: lb://vehicles:8090
          predicates:
            - Path=/api/vehicles/**
        - id: repairs
          uri: lb://repairs:8091
          predicates:
            - Path=/api/repairs/**
        - id: repairs-list
          uri: lb://repairs-list:8092
          predicates:
            - Path=/api/repair-list/**
        - id: reports
          uri: lb://reports:8093
          predicates:
            - Path=/api/reports/**
        - id: bonuses
          uri: lb://bonuses:8094
          predicates:
            - Path=/api/bonuses/**