server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repairs_list_db
    username: postgres
    password: 1234
eureka:
  instance:
    hostname: repairs-list
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
