apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonuses-deployment
  labels:
    app: bonuses-deployment
spec:
  selector:
    matchLabels:
      app: bonuses-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: bonuses-deployment
    spec:
      containers:
        - name: repairs
          image: dilget/bonuses
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_BONUSES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_BONUSES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_BONUSES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_BONUSES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_BONUSES