apiVersion: apps/v1
kind: Deployment
metadata:
  name: repairs-deployment
  labels:
    app: repairs-deployment
spec:
  selector:
    matchLabels:
      app: repairs-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: repairs-deployment
    spec:
      containers:
        - name: repairs
          image: dilget/repairs
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "8091"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIRS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIRS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REPAIRS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPAIRS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPAIRS
---
apiVersion: v1
kind: Service
metadata:
  name: repairs-service
  labels:
    app: repairs-service
spec:
  selector:
    app: repairs-deployment
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: LoadBalancer