apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
  labels:
    app: reports-deployment
spec:
  selector:
    matchLabels:
      app: reports-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-deployment
    spec:
      containers:
        - name: reports
          image: dilget/reports
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPORTS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPORTS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REPORTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPORTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPORTS